// Scene manifest for the VR Showroom — mapped to the real layout.
// left/right = turn in place; forward/back = walk to another spot.
// Set a direction to a view number to enable it, or null to disable. Ask Claude to rebuild after adding photos.

window.SHOWROOM_SCENES = [
  { id: 1, title: 'Entryway — facing the showroom', file: "images/scene-01.jpg", thumb: "images/scene-01-thumb.jpg",
    links: { forward: 8, back: null, left: 2, right: 7 } },
  { id: 2, title: 'Entryway — turning left', file: "images/scene-02.jpg", thumb: "images/scene-02-thumb.jpg",
    links: { forward: null, back: null, left: 3, right: 1 } },
  { id: 3, title: 'Entryway — toward the windows', file: "images/scene-03.jpg", thumb: "images/scene-03-thumb.jpg",
    links: { forward: null, back: null, left: 4, right: 2 } },
  { id: 4, title: 'Front window display', file: "images/scene-04.jpg", thumb: "images/scene-04-thumb.jpg",
    links: { forward: null, back: null, left: 5, right: 3 } },
  { id: 5, title: 'Facing the entrance doors', file: "images/scene-05.jpg", thumb: "images/scene-05-thumb.jpg",
    links: { forward: null, back: null, left: 6, right: 4 } },
  { id: 6, title: 'Entrance doors & welcome desk', file: "images/scene-06.jpg", thumb: "images/scene-06-thumb.jpg",
    links: { forward: null, back: null, left: 7, right: 5 } },
  { id: 7, title: 'Toward the wall display (right of entry)', file: "images/scene-07.jpg", thumb: "images/scene-07-thumb.jpg",
    links: { forward: 8, back: null, left: 1, right: 6 } },
  { id: 8, title: 'Stepping in toward the workspace', file: "images/scene-08.jpg", thumb: "images/scene-08-thumb.jpg",
    links: { forward: 9, back: 7, left: null, right: null } },
  { id: 9, title: 'Sales counter & workspace', file: "images/scene-09.jpg", thumb: "images/scene-09-thumb.jpg",
    links: { forward: null, back: 8, left: 10, right: 15 } },
  { id: 10, title: 'Workspace — toward the lounge', file: "images/scene-10.jpg", thumb: "images/scene-10-thumb.jpg",
    links: { forward: null, back: null, left: 11, right: 9 } },
  { id: 11, title: 'Foosball lounge', file: "images/scene-11.jpg", thumb: "images/scene-11-thumb.jpg",
    links: { forward: null, back: null, left: 12, right: 10 } },
  { id: 12, title: 'Lounge & banners', file: "images/scene-12.jpg", thumb: "images/scene-12-thumb.jpg",
    links: { forward: null, back: null, left: 13, right: 11 } },
  { id: 13, title: 'Turned toward the wall display', file: "images/scene-13.jpg", thumb: "images/scene-13-thumb.jpg",
    links: { forward: null, back: 31, left: 14, right: 12 } },
  { id: 14, title: 'Integrated units wall', file: "images/scene-14.jpg", thumb: "images/scene-14-thumb.jpg",
    links: { forward: null, back: null, left: 15, right: 13 } },
  { id: 15, title: 'Pathway through the display', file: "images/scene-15.jpg", thumb: "images/scene-15-thumb.jpg",
    links: { forward: 16, back: null, left: 9, right: 14 } },
  { id: 16, title: 'Walking through the display', file: "images/scene-16.jpg", thumb: "images/scene-16-thumb.jpg",
    links: { forward: 17, back: 15, left: null, right: null } },
  { id: 17, title: 'Back side of display — seats', file: "images/scene-17.jpg", thumb: "images/scene-17-thumb.jpg",
    links: { forward: 25, back: 16, left: 18, right: 24 } },
  { id: 18, title: 'Toward the espresso lounge', file: "images/scene-18.jpg", thumb: "images/scene-18-thumb.jpg",
    links: { forward: null, back: null, left: 19, right: 17 } },
  { id: 19, title: 'Entertainment space', file: "images/scene-19.jpg", thumb: "images/scene-19-thumb.jpg",
    links: { forward: null, back: null, left: 20, right: 18 } },
  { id: 20, title: 'Entertainment — left wall', file: "images/scene-20.jpg", thumb: "images/scene-20-thumb.jpg",
    links: { forward: null, back: null, left: 21, right: 19 } },
  { id: 21, title: 'Beach canvas wall', file: "images/scene-21.jpg", thumb: "images/scene-21-thumb.jpg",
    links: { forward: null, back: null, left: 22, right: 20 } },
  { id: 22, title: 'Turning back across the floor', file: "images/scene-22.jpg", thumb: "images/scene-22-thumb.jpg",
    links: { forward: null, back: null, left: 23, right: 21 } },
  { id: 23, title: 'Looking toward the pathway', file: "images/scene-23.jpg", thumb: "images/scene-23-thumb.jpg",
    links: { forward: 16, back: null, left: 24, right: 22 } },
  { id: 24, title: 'Back side display — bidet seats', file: "images/scene-24.jpg", thumb: "images/scene-24-thumb.jpg",
    links: { forward: 25, back: null, left: 17, right: 23 } },
  { id: 25, title: 'Open-box units', file: "images/scene-25.jpg", thumb: "images/scene-25-thumb.jpg",
    links: { forward: null, back: 24, left: 26, right: 32 } },
  { id: 26, title: 'Staff entrance & photo studio', file: "images/scene-26.jpg", thumb: "images/scene-26-thumb.jpg",
    links: { forward: null, back: null, left: 27, right: 25 } },
  { id: 27, title: 'Photography studio', file: "images/scene-27.jpg", thumb: "images/scene-27-thumb.jpg",
    links: { forward: null, back: null, left: 28, right: 26 } },
  { id: 28, title: 'Studio & entertainment space', file: "images/scene-28.jpg", thumb: "images/scene-28-thumb.jpg",
    links: { forward: null, back: null, left: 29, right: 27 } },
  { id: 29, title: 'Entertainment & display back', file: "images/scene-29.jpg", thumb: "images/scene-29-thumb.jpg",
    links: { forward: 21, back: null, left: 30, right: 28 } },
  { id: 30, title: 'Back of the display unit', file: "images/scene-30.jpg", thumb: "images/scene-30-thumb.jpg",
    links: { forward: null, back: null, left: 31, right: 29 } },
  { id: 31, title: 'Pathway to front of display', file: "images/scene-31.jpg", thumb: "images/scene-31-thumb.jpg",
    links: { forward: 13, back: null, left: 32, right: 30 } },
  { id: 32, title: 'Open-box units (far corner)', file: "images/scene-32.jpg", thumb: "images/scene-32-thumb.jpg",
    links: { forward: null, back: null, left: 25, right: 31 } }
];
